name: test
on:
  push:
    branches:
      - "master"
      - "release-*"
  pull_request:
    branches: [ "*" ]
jobs:
  # codegen:
  #   name: Codegen
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Restore go build cache
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/go-build
  #         key: ${{ runner.os }}-go-build-v1-${{ hashFiles('**/go.mod') }}
  #     - name: Setup Golang
  #       uses: actions/setup-go@v3.2.0
  #       with:
  #         go-version: "1.19"
  #     - name: Add bins to PATH
  #       run: |
  #         echo /home/runner/go/bin >> $GITHUB_PATH
  #         echo /usr/local/bin >> $GITHUB_PATH
  #     - name: Install protoc
  #       run: |
  #         set -eux -o pipefail
  #         PROTOC_VERSION=3.11.1
  #         PROTOC_ZIP=protoc-$PROTOC_VERSION-linux-x86_64.zip
  #         curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.1/$PROTOC_ZIP
  #         sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  #         sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
  #         sudo chmod +x /usr/local/bin/protoc
  #         sudo find /usr/local/include -type f | xargs sudo chmod a+r
  #         sudo find /usr/local/include -type d | xargs sudo chmod a+rx
  #         rm -f $PROTOC_ZIP
  #         ls /usr/local/include/google/protobuf/
  #     - name: Install pandoc
  #       run: |
  #         set -eux -o pipefail
  #         PANDOC_VERSION=2.17.1
  #         PANDOC_ZIP=pandoc-$PANDOC_VERSION-linux-amd64.tar.gz
  #         curl -OL https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/$PANDOC_ZIP
  #         sudo tar xvzf $PANDOC_ZIP --strip-components 1 -C /usr/local
  #         rm -f $PANDOC_ZIP
  #         echo /usr/local/pandoc-$PANDOC_VERSION/bin >> $GITHUB_PATH
  #     - name: Get dependencies
  #       run: go mod download
  #     - name: Make codegen
  #       run: |
  #         echo 'GOPATH=/home/runner/go' >> $GITHUB_ENV
  #         make -B codegen
  #     - name: Ensure nothing changed
  #       run: git diff --exit-code

  # unit-tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - name: Set up Go 1.x
  #       uses: actions/setup-go@v3.2.0
  #       with:
  #         go-version: "1.19"
  #       id: go
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v3
  #     - name: Restore Go build cache
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/go-build
  #         key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}
  #     - name: Get dependencies
  #       run: go mod download
  #     - name: Test
  #       run: make test

  # lint:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   env:
  #     GOPATH: /home/runner/go
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Golang
  #       uses: actions/setup-go@v3.2.0
  #       with:
  #         go-version: "1.19"
  #     - name: Restore Go build cache
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/go-build
  #         key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}
  #     - run: make lint
  #     - run: git diff --exit-code

  argoevents-image:
    name: argoevents-image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build argoevents image
        run: |
          make image
          docker save quay.io/argoproj/argo-events:latest > /tmp/argoevents_image.tar
      - name: Archive image
        uses: actions/upload-artifact@v3
        with:
          name: argoevents
          path: /tmp/argoevents_image.tar
          if-no-files-found: error

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [ argoevents-image ]
    env:
      KUBECONFIG: /home/runner/.kubeconfig
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - driver: stan
          - driver: jetstream
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore go build cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v2-${{ hashFiles('**/go.mod') }}
      - name: Setup Golang
        uses: actions/setup-go@v3.2.0
        with:
          go-version: "1.19"
      - name: Add bins to PATH
        run: |
          echo /home/runner/go/bin >> $GITHUB_PATH
          echo /usr/local/bin >> $GITHUB_PATH
      # - name: Build image
      #   run: |
      #     make image
      #     docker save quay.io/argoproj/argo-events:latest > /tmp/argoevents_image.tar
      - name: Install and start K3S
        run: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.2+k3s1 INSTALL_K3S_CHANNEL=stable INSTALL_K3S_EXEC=--docker K3S_KUBECONFIG_MODE=644 sh -
          until kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml cluster-info ; do sleep 10s ; done
          cp /etc/rancher/k3s/k3s.yaml /home/runner/.kubeconfig
          echo "- name: fake_token_user" >> $KUBECONFIG
          echo "  user:" >> $KUBECONFIG
          echo "    token: xxxxxx" >> $KUBECONFIG
          until kubectl cluster-info ; do sleep 10s ; done
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: argoevents
          path: /tmp
      # - name: Run tests
      #   uses: debianmaster/actions-k3s@v1.0.5
      #   with:
      #     version: 'v1.25.0-k3s1'
      - run: |
          docker load < /tmp/argoevents_image.tar
          make start
          EventBusDriver=${{ matrix.driver }} make test-functional
      # - name: Create cluster
      #   uses: helm/kind-action@v1.4.0
      #   with:
      #     cluster_name: ${{ matrix.driver }}
      # - name: Build Argo Events
      #   env:
      #     GOPATH: /home/runner/go
      #   run: VERSION=${{ github.sha }} make image
      # - name: Load docker image
      #   run: kind load docker-image quay.io/argoproj/argo-events:${{ github.sha }} --name ${{ matrix.driver }}
      # - name: Start Argo Events
      #   env:
      #     GOPATH: /home/runner/go
      #   run: VERSION=${{ github.sha }} make start
      # - name: Run tests
      #   env:
      #     GOPATH: /home/runner/go
      #   run: EventBusDriver=${{ matrix.driver }} make test-functional
